```{r include=FALSE}
knitr::opts_chunk$set(message=FALSE, echo=FALSE, warning=FALSE, fig.width=10)
```

```{r}
library(ape)
library(ggplot2)
library(dplyr)
library(magrittr)
library(tidyr)
library(cluster)
```

```{r}
winsor <- function(x, u){
  if(any(x>u)) x[x>u] = u
  x
}
```

```{r}
kmvar <- function(mat, clsize=10, method=c('random','maxd', 'mind', 'elki')){
  k = ceiling(nrow(mat)/clsize)
  km.o = kmeans(mat, k)
  labs = rep(NA, nrow(mat))
  centd = lapply(1:k, function(kk){
    euc = t(mat)-km.o$centers[kk,]
    sqrt(apply(euc, 2, function(x) sum(x^2)))
  })
  centd = matrix(unlist(centd), ncol=k)
  clsizes = rep(0, k)
  if(method[1]=='random'){
    ptord = sample.int(nrow(mat))
  } else if(method[1]=='elki'){
    ptord = order(apply(centd, 1, min) - apply(centd, 1, max))
  } else if(method[1]=='maxd'){
    ptord = order(-apply(centd, 1, max))
  } else if(method[1]=='mind'){
    ptord = order(apply(centd, 1, min))
  } else {
    stop('unknown method')
  }
  for(ii in ptord){
    bestcl = which.max(centd[ii,])
    labs[ii] = bestcl
    clsizes[bestcl] = clsizes[bestcl] + 1
    if(clsizes[bestcl] >= clsize){
      centd[,bestcl] = NA
    }
  }
  return(labs)
}
```

```{r}
N = 1000
mat = matrix(rnorm(2*N), N)
## Outliers
OL = sample.int(N, 100)
mat[OL,] = runif(length(OL), 2, 5)*mat[OL,]
## 4 groups
GPx = rep(4*c(0,0,0,1), c(2/5, 1/5, 1/5, 1/5)*N)
GPy = rep(4*c(0,1,2,1), c(2/5, 1/5, 1/5, 1/5)*N)
mat[,1] = GPx + mat[,1]
mat[,2] = GPy + mat[,2]
mat %>% as.data.frame %>% ggplot(aes(V1, V2)) + geom_point(alpha=.5) + theme_bw()
```

```{r}
nnit <- function(mat, clsize = 10, method=c('random','maxd', 'mind')){
  clsize.rle = rle(as.numeric(cut(1:nrow(mat), ceiling(nrow(mat)/clsize))))
  clsize = clsize.rle$lengths
  lab = rep(NA, nrow(mat))
  dmat = as.matrix(dist(mat))
  cpt = 1
  while(sum(is.na(lab)) > 0){
    lab.ii = which(is.na(lab))
    dmat.m = dmat[lab.ii,lab.ii]
    if(method[1]=='random'){
      ii = sample.int(nrow(dmat.m),1)
    } else if(method[1]=='maxd'){
      ii = which.max(rowSums(dmat.m))
    } else if(method[1]=='mind'){
      ii = which.min(rowSums(dmat.m))
    } else {
      stop('unknown method')
    }
    lab.m = rep(NA, length(lab.ii))
    lab.m[head(order(dmat.m[ii,]), clsize[cpt])] = cpt
    lab[lab.ii] = lab.m
    cpt = cpt + 1
  }
  if(any(is.na(lab))){
    lab[which(is.na(lab))] = cpt
  }
  lab
}
```

```{r}
clsize = 21
## Cluster statistics
clstats <- function(mat, cls){
  dmat = as.matrix(dist(mat))
  sk <- silhouette(as.numeric(factor(cls)), dmatrix=dmat)
  mean.sk = mean(sk[,3])
  ll = lapply(unique(cls), function(cl){
    cl.ii = which(cls==cl)
    d = as.dist(dmat[cl.ii, cl.ii])
    tibble(lab=cl, max.dist=max(d), mean.dist=mean(d), size=length(cl.ii), mean.cl.sil=mean(sk[cl.ii, 3]), mean.sil=mean.sk)
  })
  do.call(rbind, ll)
}

kmv.l = lapply(c('random', 'maxd', 'mind', 'elki'), function(meth){
  lab = kmvar(mat, clsize, method=meth)
  clstats(mat, lab) %>% mutate(method=meth, strategy='Kmeans-var')
})

nn.l = lapply(c('random', 'maxd', 'mind'), function(meth){
  lab = nnit(mat, clsize, method=meth)
  clstats(mat, lab) %>% mutate(method=meth, strategy='nearest neighbors')
})

cls.df = do.call(rbind, c(kmv.l, nn.l))
```

```{r}
ggplot(cls.df, aes(x=method, y=winsor(size, 3*clsize))) + geom_boxplot() + theme_bw() +
  geom_hline(yintercept=clsize, linetype=2) +
  facet_grid(.~strategy, space='free', scales='free') +
  ylab(paste0('cluster size (winsorized at ', 3*clsize, ')')) +
  theme(axis.text.x=element_text(hjust=1, vjust=1, angle=70)) +
  scale_y_continuous(breaks=seq(0,200,10))
```

```{r}
## Average distance between points in a cluster
ggplot(cls.df, aes(x=method, y=mean.dist)) + geom_boxplot() + theme_bw() +
  theme(axis.text.x=element_text(hjust=1, vjust=1, angle=70)) +
  facet_grid(.~strategy, space='free', scales='free') + ylab('average pairwise distance')
## Maximum distance between two points in a cluster
ggplot(cls.df, aes(x=method, y=max.dist)) + geom_boxplot() + theme_bw() +
  theme(axis.text.x=element_text(hjust=1, vjust=1, angle=70)) +
  facet_grid(.~strategy, space='free', scales='free') + ylab('maximum pairwise distance')
```

```{r}
## Median after filtering for NA and infinite values
medianFilt <- function(x){
  median(x[which(!is.infinite(x) & !is.na(x))])
}
## Summary 
cls.df %>% select(-lab, -size, -mean.sil, -mean.cl.sil) %>% group_by(method, strategy) %>%
  summarize_all(medianFilt) %>% gather(variable, value, -method, -strategy) %>%
  mutate(variable=factor(variable, levels=c('mean.dist', 'max.dist'),
                         labels=c('average pairwise distance',
                                  'maximum pairwise distance'))) %>% 
  ggplot(aes(x=paste(strategy, method), y=value, fill=strategy)) +
  geom_bar(stat='identity') + facet_wrap(~variable, scales='free') + theme_bw() +
  theme(axis.text.x=element_text(hjust=1, vjust=1, angle=70)) +
  xlab('') + ylab('median per-cluster value')
```

